### ISSUE TITLE
Some ideas for strategy

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarchr#1]
original doc: https://docs.google.com/document/d/1cbNP45X32G8BEoJgpX91gUANB5_CVCZARPh51RVgBA8/edit

This document is for rough notes on approaches for exposing Monarch via R

1. Fully featured R library with graph logic in R
2. thin wrapper onto new Monarch API
3. This wrapper onto OAK, which itself wraps Monarch API

## Fully featured R library

 The idea would be to have lots of ontology logic implemented in R. This would essentially be OAK in R.

I don’t think we should pursue this unless there is someone who has the time and resources, a strong vision and extensive experience of building similar libraries

## Thin wrapper onto Monarch API

This would be a very lightweight layer that would mostly be geared around obtaining dataframes for genes, diseases, etc. It would have minimal logic. It could even be autoderived via swagger2R.

All logic would be server side. The R would mostly be retrieval

## Thin wrapper onto OAK

This would require two new pieces
FastAPI layer onto OAK
An OAK adapter for the new Monarch API

However, both of these are already things we want.

There may be efficiency considerations with so many layers. There would need to be some thinking about the generic FastAPI layer for OAK (e.g. OAK is naturally sync; things like connecting to a sqlite for the first time incur an initial time overhead)

**Comment by monicacecilia** [comment]
Dear @oneilsh, 

Reaching out to check on the status of implementing this strategy for the release of a Monarch's R package.
I would like to kindly ask you to please share with us the details of your timeline and the deliverables you have determined to complete these tasks. 
As well, it would be helpful to understand which parts of this strategy are currently on the horizon and whether or not a decision was made to turn down/modify some of them. 

Looking forward to hearing your update! Thank you! 🌷

**Comment by oneilsh** [comment]
Closing here - where we ended up: main functionality uses Monarch Neo4j endpoint (and Neo4j-hosted KGX KGs in general, with paging and limits for efficiency), and a framework providing the same core API for KGX graphs from kghub.org. Monarch-specific functionality (search and semantic similarity) is a thin-wrapper around the monarch API. See issue #16 and (big) PR #18
