### ISSUE TITLE
Main branch docs not building

### ISSUE THREAD

**Issue by oneilsh** [monarch-initiative/monarchr#17]
Something isn't right with the main branch, the Get Started and other pages are 404ing: https://monarch-initiative.github.io/monarchr/articles/monarchr

It appears to be something in the rworkflows build, but I'm not savvy to debug - I cleaned up some of the errors and warnings so the R CMD CHECK will pass (there are still a few Notes to debug), but it appears not enough, the Ubuntu build (only) is throwing an error:

```
Error in `loadNamespace()`:
! there is no package called 'rworkflows'
```

@bschilder could you take a look?

**Comment by bschilder** [comment]
This is happening because the README calls rworkflows to build the badges: 
https://github.com/monarch-initiative/monarchr/blob/7c24199c45c47bf8949dfa966a0a83400b476349/README.Rmd#L3

The options in this case would be to either:
1. add `rworkflows` as a `Suggest` in the `monarchr` DESCRIPTION
2. copy and paste the output of `rworkflows::use_badges` into the header of the README.Rmd

**Comment by oneilsh** [comment]
Ahah, thank you. I am still getting used to some of these finer points of R package devel, I'm a good audience for `rworkflows` :) I am trying option 1 now, still getting an error, this time on Windows and Mac but not Ubuntu:

```
Package suggested but not available: ‘rworkflows’
```

I'll keep trying, might resort to option 2 but having badges as part of the automation is a nice feature.

Somewhat related, I noticed that CHECK is giving a Note about `Non-standard file/directory found at top level: ‘README.Rmd’` - is that expected? (The other notes are just cleanups needed, I'm also using a `.env` in this branch at the top level that is also throwing a Note. I mostly want this branch to build the vignette for browsing while I focus on making the engines branch nice and clean, I'll avoid `.env` there.)

**Comment by oneilsh** [comment]
Ok, I managed to hack this together, by removing (for now) the build checks for OSX and Windows. I also realized the github repo pages deployment was setup to use the `main` branch as opposed to the `gh-pages` branch, so I updated that, and the website and vignette are back alive :)

**Comment by bschilder** [comment]
> Ahah, thank you. I am still getting used to some of these finer points of R package devel, I'm a good audience for `rworkflows` :) I am trying option 1 now, still getting an error, this time on Windows and Mac but not Ubuntu:
> 
> ```
> Package suggested but not available: ‘rworkflows’
> ```

This is weird for a couple of reasons. The rworkflows GH Action should automatically install rworkflows from GH on each OS. And even if that isn't working, installing monarchr should trigger the installation of all suggests anyways. Will look into this further from the rworkflows side.

I'm also seeing this error, which says its installed but the wrong version? Which doesn't make sense bc we don't have any min/max version limits specified in the monarchr DESCRIPTION:
https://github.com/monarch-initiative/monarchr/actions/runs/9571102606/job/26387370716#step:4:873

> I'll keep trying, might resort to option 2 but having badges as part of the automation is a nice feature.
> 
> Somewhat related, I noticed that CHECK is giving a Note about `Non-standard file/directory found at top level: ‘README.Rmd’` - is that expected? (The other notes are just cleanups needed, I'm also using a `.env` in this branch at the top level that is also throwing a Note. I mostly want this branch to build the vignette for browsing while I focus on making the engines branch nice and clean, I'll avoid `.env` there.)

This one is much more straightforward, I simply forgot to append the `.Rbuildignore` file. Adding this line to it should fix it:
```
^README.Rmd
```
