### ISSUE TITLE
Identify stable live KG unit tests

### ISSUE THREAD

**Issue by oneilsh** [monarch-initiative/monarchr#21]
Many of the unit tests for the Neo4j and Monarch engines use the Monarch Neo4j endpoint and compared returned results against expected result. Since this may change over time, the expected results may as well. Not sure the best way to address this currently, other than finding areas of the Monarch KG that are likely to be stable over time. (For comparison, the file-based engine uses a copy of the the MONDO KG included specifically for unit testing.)

**Comment by bschilder** [comment]
> Many of the unit tests for the Neo4j and Monarch engines use the Monarch Neo4j endpoint and compared returned results against expected result. Since this may change over time, the expected results may as well

I usually try to write tests that are a bit flexible. For example, if a query returns 342 results, I might use:
```R
testthat::expect_gte(length(result), 300)
testthat::expect_lte(length(result), 500)
```

Or if I'm testing against the contents of the result, I'll test whether items that are guaranteed to be included (or at least very likely) are there.
