### ISSUE TITLE
Coordinating R package projects

### ISSUE THREAD

**Issue by bschilder** [monarch-initiative/monarchr#7]
Hi there, 

I'm in the process of developing another R package, [`KGExplorer`](https://github.com/neurogenomics/KGExplorer), which seeks to merge knowledge graphs from multiple biomedical resources, with a special focus on Monarch to start. I'm quite partial to the `tidygraph` representation and plan to use that as one of the primary object classes, in addition to the `ontology_DAG` class within [`simona`](https://bioconductor.org/packages/release/bioc/html/simona.html) for ontologies.

Some potential integrations:
- https://github.com/neurogenomics/KGExplorer/issues/1

<hr>

I was also just having a discussion with @charlieccarey about their R package of the same name:
- https://github.com/charlieccarey/monarchr/issues/10

@charlieccarey's package has some nice functionalities like searching for specific types of interactions, e.g. [`bioentity_interactions_assoc_w_gene`](https://github.com/charlieccarey/monarchr/blob/474e5a926341c67bc0546a2da23b67b9b6dddc6c/R/monarchr.R#L381) 

I'm mainly posting here to see if there's way we could coordinate our efforts. I haven't explored the package in your repo yet but would be happy to make contributions if there's room for it.

All the best, 
Brian
_______________
Brian M. Schilder
PhD Candidate
Neurogenomics Lab
Faculty of Medicine, Department of Brain Sciences
UK Dementia Research Institute, Imperial College London
CV | [bschilder.github.io/CV/CV](https://bschilder.github.io/CV/CV.html)
LinkedIn | [linkedin.com/in/brian-schilder](https://www.linkedin.com/in/brian-schilder/)
Website I | [bschilder.github.io/BMSchilder](https://bschilder.github.io/BMSchilder/)
Twitter | [twitter.com/BMSchilder](http://www.twitter.com/BMSchilder)
Lab | [neurogenomics.co.uk](https://www.neurogenomics.co.uk/)

**Comment by bschilder** [comment]
@oneilsh would you be correct contact point for this?

**Comment by bschilder** [comment]
Perhaps @cmungall as well

**Comment by oneilsh** [comment]
@bschilder thank you for the flag! Yes that would be me :) CCing @cmungall, @kevinschaper, and @sagehrke FYI

I think your proposal to coordinate sounds good, we've been planning something specifically for Monarch, but thinking more generally or at least doing so in a way that can support or integrate with other KGs would certainly not hurt. As the commits reveal I haven't worked on this repo in a while and there's not much functionality implemented yet.

I'm also a fan of `tidygraph` and had planned to use it heavily, building a small Monarch-specific DSL; or more KG-generic, which sounds like your interest. See this little [user story](https://github.com/monarch-initiative/monarchr/blob/user_story/meta/user_story.md) example (but don't take it too seriously, especially the proposed data model). I hadn't seen simona before, I presume you mean [this one](https://bioconductor.org/packages/release/bioc/html/simona.html), I don't have a lot of experience with ontologies and KGs so I'm not as familiar with the available packages, especially in R. Our lab and collaborators do quite a lot of good work in Python.

We've gone back and forth a bit on the best way to get the data to the package, between bulk file download, something like a bioconductor data package, or using the REST API (ala @charlieccarey's package, but there've been big graph and API updates recently as you've noticed). It's on our [short-term plans](https://github.com/monarch-initiative/monarch-app/issues/483) however to release a neo4j endpoint for the KG, which I think will be the way to go.

So yeah, let's build slick KG packages for R!

**Comment by bschilder** [comment]
> @bschilder thank you for the flag! Yes that would be me :) CCing @cmungall, @kevinschaper, and @sagehrke FYI
> 
> I think your proposal to coordinate sounds good, we've been planning something specifically for Monarch, but thinking more generally or at least doing so in a way that can support or integrate with other KGs would certainly not hurt. As the commits reveal I haven't worked on this repo in a while and there's not much functionality implemented yet.

Amazing, thanks for the positive response @oneilsh ! 

I think it might be nice to keep it modular, and have `monarchr` as it's own package that a meta-package can call as a dependency. Prevents the code base from getting exceedingly complicated and lets you unit test your packages a bit easier in some ways. I have a CI-assistant package for making this kind of multi-package maintenance a bit more manageable, called [`rworkflows`](https://github.com/neurogenomics/rworkflows).

> I'm also a fan of `tidygraph` and had planned to use it heavily, building a small Monarch-specific DSL; or more KG-generic, which sounds like your interest. See this little [user story](https://github.com/monarch-initiative/monarchr/blob/user_story/meta/user_story.md) example (but don't take it too seriously, especially the proposed data model). I hadn't seen simona before, I presume you mean [this one](https://bioconductor.org/packages/release/bioc/html/simona.html), I don't have a lot of experience with ontologies and KGs so I'm not as familiar with the available packages, especially in R. Our lab and collaborators do quite a lot of good work in Python.

Yes, thats' the one! Sorry, pasted the wrong link. `simona` seems to be quite well maintained and has extensive functions for computing every variety of similarity matrix you can imagine. I'm in the process of transitioning my HPO-specific package ([`HPOExplorer`](https://github.com/neurogenomics/HPOExplorer/issues/31)) to using this format instead of [`ontologyIndex`](https://cran.r-project.org/web/packages/ontologyIndex/index.html).


> We've gone back and forth a bit on the best way to get the data to the package, between bulk file download, something like a bioconductor data package, or using the REST API (ala @charlieccarey's package, but there've been big graph and API updates recently as you've noticed). It's on our [short-term plans](https://github.com/monarch-initiative/monarch-app/issues/483) however to release a neo4j endpoint for the KG, which I think will be the way to go.

Atm, `KGExplorer` only pulls in the bulk data files, which isn't ideal for all use cases but surprisingly usable. Would definitely be worth doing some benchmarking to see which approach is fastest, but I do really like the idea of using neo4j as this seems perfectly suited for the Monarch db use case. 

> So yeah, let's build slick KG packages for R!

Heck yeah! Perhaps the next steps would be have a meeting to flesh out the plans and see what the best way to tackle them might be. 

I'd be happy to send out a meeting scheduler invite to figure out when that might work best (after the holidays of course).

**Comment by oneilsh** [comment]
@bschilder happy post-holidays :) 

I would definitely be up for a brainstorming session, it would be nice to get your perspective. Can you send me an email to my shawn@tislab.org address to set up a time and zoom?

**Comment by bschilder** [comment]
> @bschilder happy post-holidays :)
Hope you had a great holiday break yourself :) 

> I would definitely be up for a brainstorming session, it would be nice to get your perspective. Can you send me an email to my [shawn@tislab.org](mailto:shawn@tislab.org) address to set up a time and zoom?

Amazing, thanks! I'll send you an email now. If anyone else would like to join the call, do let me know and I can add your emails as well @cmungall @kevinschaper @sagehrke @charlieccarey

**Comment by sagehrke** [comment]
Thank you @bschilder and @oneilsh! I will sit this one out, but I am excited to hear what comes of this call. 👍🏼

**Comment by monicacecilia** [comment]
Dear @oneilsh, could I kindly ask if you could please share an update on where this coordination effort ended up? Are there next steps?

**Comment by oneilsh** [comment]
@bschilder thank you for your collaboration and help so far! I hope we continue to build together - I'm going through and closing old tickets, and I'll be opening up some others for specific things, please feel free to add :)

**Comment by bschilder** [comment]
> @bschilder thank you for your collaboration and help so far! I hope we continue to build together - I'm going through and closing old tickets, and I'll be opening up some others for specific things, please feel free to add :)

Sounds great! Excited to help keep this moving forward!
